<?php
/**
 * @file
 * Code for the Help feature.
 */

include_once 'hr_help.features.inc';

function hr_help_block_info() {
  $blocks['hr_help'] = array(
    'info' => t('Help block'),
  );
  return $blocks;
}

function hr_help_block_view($delta = '') {
  global $user;
  $block = array();
  switch ($delta) {
    case 'hr_help':
      $tours = array();
      $all_tours = bootstrap_tour_load_all();
      foreach ($all_tours as $key => $tour) {
        if (empty($tour->roles)) {
          $tours[$key] = $tour;
        }
        else {
          $roles = explode(',', $tour->roles);
          foreach ($roles as $role) {
            if (in_array($role, array_keys($user->roles))) {
              $tours[$key] = $tour;
            }
          }
        }
      }
      if (!empty($tours)) {
        $block['content'] = '<div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-question fa-lg"></i>
          </button>
          <ul class="dropdown-menu">';
        foreach ($tours as $key => $tour) {
          $block['content'] .= '<li>'.l(t($tour->title), $tour->steps[0]['path'], array('query' => array('tour' => $key))).'</li>';
        }
        $block['content'] .= '</ul></div>';
      }
      break;
  }
  return $block;
}

